### ISSUE TITLE
SyntaxError when running from script

### ISSUE THREAD

**Issue by juanfrans** [tangrams/bundler#11]
Hi, I'm trying to run the bundler without running it locally and I get the following error:
`File "/dev/fd/11", line 260`
`    print WARN_COLOR + "Draw Rule is none for key ", key, " in layer ", str(layerNode) + NORM_COLOR`
`                   ^`
`SyntaxError: invalid syntax`

The little `^` is underneath the `R` from `WARN_COLOR`.

I'm running it on python3.7.2

Thanks!

**Comment by nvkelso** [comment]
Hard to tell without seeing your YAML. Feel free to post to private GIST and send link to my email nvkelso @ gmail.

**Comment by matteblair** [comment]
@juanfrans This is due to a Python 2/3 incompatibility. This script is only compatible with Python 2.x, if you run it with Python 3 you'll get errors like the one you reported.

**Comment by nvkelso** [comment]
Updated README to reflect the expected Python version in https://github.com/tangrams/bundler/commit/02643878a03e55174643850d14d1d59e5e5ad371#diff-04c6e90faac2675aa89e2176d2eec7d8.

@juanfrans Let us know if it works for you in Python 2.x!

**Comment by juanfrans** [comment]
@nvkelso & @matteblair Thanks! That worked.
