### ISSUE TITLE
Add YAML > JSON converter option

### ISSUE THREAD

**Issue by nvkelso** [tangrams/bundler#3]
While YAML is more human friendly to write, JSON is faster to read and can reduce app start times.

Once JSON scene files are supported in Tangram as an external source it would be good to add option to bundler to do the JSON conversion on ZIP export.

See also:

- https://github.com/tangrams/tangram-es/issues/1004#issuecomment-260824779

**Comment by tallytalwar** [comment]
We can consider this done, i suppose.
